### ISSUE TITLE
[Feature Request]: Config or Datapack for spawn weight

### ISSUE THREAD

**Issue by L0WSP0T** [AlexNijjar/Subterrestrial#6]
### Is your feature request related to a problem?

Currently I think the structure overspawns a bit. I find 1 in almost each large cave I come across, I love the mod but the structure being repetitive makes it lose its touch imo

### Solution(s)

Make a config or datapack for users to edit the spawn weights themselves.

### Describe alternatives you've considered

Make them spawn slightly less by default

### Mod Version

1.18.2

### Mod Loader Version

40.2.1

### Mod Loader

Forge

### Additional context

I am making a modpack pls consider this thanks!

**Comment by AlexNijjar** [comment]
subterrestrial uses the vanilla datapack system to add structures and change their rarity. so to increase the rarity, you'd override this in your pack and increase the spacing and separation https://github.com/AlexNijjar/Subterrestrial/blob/1.19/common/src/main/resources/data/subterrestrial/worldgen/structure_set/default_cabin.json

**Comment by L0WSP0T** [comment]
The link no longer works btw^
